name: hyperlink
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  nsd: ^5.0.1
  network_info_plus: ^5.0.3
  path_provider: ^2.1.6
  permission_handler: ^11.3.1
  pointycastle: ^3.9.1
  convert: ^3.1.1
  uuid: ^4.4.0
  logger: ^2.4.0
  device_info_plus: ^11.5.0
  isar: ^4.0.0-dev.3
  isar_flutter_libs: ^4.0.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
